name: "impact_elt"
version: "1.0.0"
config-version: 2

profile: "user"   # dbt Cloud manages this automatically

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  impact_elt:
    +materialized: table